openapi: 3.1.0
info:
  version: 1.0.0
  title: Money Guard app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of transactions app
tags:
  - name: Auth
    description: Auth operations.
  - name: User
    description: User operations.
  - name: Transactions
    description: Operations about transactions.
servers:
  - url: 'https://moneyguard-group-06.onrender.com'
  - url: 'http://localhost:3000'
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /transactions:
    get:
      $ref: ../swagger/paths/transactions/get.yaml
    post:
      $ref: ../swagger/paths/transactions/post.yaml
  /transactions/{id}:
    patch:
      $ref: ../swagger/paths/transactions/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/transactions/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
